# Generated by Django 2.2 on 2019-04-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.CharField(default=None, max_length=36),
            preserve_default=False,
        ),
    ]
